name: Auto Label Issues and Pull Requests

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Label Issue or PR based on title
        uses: actions/github-script@v9
        with:
          script: |
            const isPR = context.payload.pull_request !== undefined;
            const isIssue = context.payload.issue !== undefined
            
            if (!isPR && !isIssue) {
              console.log('Isn't PR or Issue...');
              return;
            }
            
            const title = isPR ? context.payload.pull_request.title : context.payload.issue.title;
            const number = isPR ? context.payload.pull_request.number : context.payload.issue.number;
            
            let labels = [];
            
            if (title.includes('[Bug]')) labels.push('bug');
            if (title.includes('[Feature]')) labels.push('feature');
            if (title.includes('[Enhancement]')) labels.push('enhancement');
            if (title.includes('[Refactor]')) labels.push('refactor');
            if (title.includes('[Documentation]')) labels.push('documentation');
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
              console.log(`✅ Added Labels: ${labels.join(', ')}`);
            } else {
              console.log(`ℹ️ No Labels for title: "${title}"`);
            }